#!/usr/bin/env bash

# script name: rofi-powermenu
# description: choose from power options and enact the choice
# usage: rofi-powermenu
# dependencies: rofi, systemd, betterlockscreen, bspwm

rofi_dir="$HOME/.config/rofi/"

lock=" Lock"
sleep=" Sleep"
logout="󰍃 Logout"
restart=" Restart"
shutdown="⏻ Shutdown"
cancel="󰕌 Cancel"

options="$lock\n$sleep\n$logout\n$restart\n$shutdown\n$cancel"

confirm() {
	confirmation="$(echo -e "Yes\nNo" | rofi -dmenu -theme "$rofi_dir/scripts/wayland/confirm-menu.rasi" &)"
	if [[ "$confirmation" != "Yes" ]]; then
		exit 0
	fi
}

answer="$(echo -e "$options" | rofi -dmenu -i -theme "$rofi_dir/scripts/wayland/powermenu.rasi")"

case $answer in
$lock)
	confirm
	# playerctl pause
	betterlockscreen -l dimblur
	;;
$sleep)
	confirm
	xset -display :0 dpms force off
	# notify-send "System slept! (unimplemented)"
	#systemctl suspend --NVIDIA OPEN DRIVERS DON'T SUSPEND
	;;
$logout)
	confirm
	bspc quit
	;;
$restart)
	confirm
	systemctl reboot
	;;
$shutdown)
	confirm
	systemctl poweroff
	;;
$cancel)
	exit 0
	;;
esac
