#!/usr/bin/env zsh

# script to search path with fzf & rg
fp () {
    # make sure fzf is installed
    if [[ -z $commands[fzf] ]]; then
        echo 'fzf is not installed.'
        return 1
    fi

    # make sure ripgrep is installed
    if [[ -z $commands[rg] ]]; then
        echo 'ripgrep is not installed.'
        return 1
    fi

    # save currently selected path as a variable
    LOCATION=$(echo "$PATH" | tr ':' '\n' | eval "fzf $FZF_DEFAULT_OPTS --header='[find:path]'")

    # recursively search path
    if test "$(echo "$LOCATION" | wc -w)" -eq 1; then
        COMMAND=$(rg --files "$LOCATION" | rev | cut -d'/' -f1 | rev | tr ' ' '\n' | eval "fzf $FZF_DEFAULT_OPTS --header='[find:exe] => $LOCATION'")
        if test "$(echo "$COMMAND" | wc -w)" -eq 1; then
            echo "$LOCATION $COMMAND"
        else
            fp
        fi
    fi
}

