#!/usr/bin/env zsh

# script to kill a process found with fzf
kp () {
    # make sure fzf is installed
    if [[ -z $commands[fzf] ]]; then
        echo 'fzf is not installed.'
        return 1
    fi

    # find process and kill it
    KP_PID=$(ps -ef | sed 1d | eval "fzf $FZF_DEFAULT_OPTS -m --header='[kill:process]'" | awk '{print $2}')

    if test -n "$KP_PID"; then
        if test -n "$1"; then
            echo "$KP_PID" | xargs kill "$1"
        else
            echo "$KP_PID" | xargs kill -9
        fi
    fi
}

