#!/bin/bash

wallpaper_dir="$HOME/Pictures/Wallpaper"

export SWWW_TRANSITION=wipe
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_STEP=2
export SWWW_TRANSITION_ANGLE=30

list_wallpapers() {
	find "$wallpaper_dir" -maxdepth 1 -type f -printf "%P\n" |
		while read wallpaper; do
			echo -en "$wallpaper\x00icon\x1f$wallpaper_dir/$wallpaper\n"
		done
}

wallpaper=$(list_wallpapers | rofi -dmenu -theme ~/.config/rofi/scripts/wayland/wallpapers.rasi)

if [ -f "$wallpaper_dir/$wallpaper" ]; then
	swww img \
		$wallpaper_dir/$wallpaper

	notify-send "Switched wallpaper to $wallpaper!" -i $wallpaper_dir/$wallpaper
fi
