#!/usr/bin/env bash

rofi_dir="$HOME/.config/rofi/"

lock=" Lock"
sleep=" Sleep"
logout="󰍃 Logout"
restart=" Restart"
shutdown="⏻ Shutdown"
cancel="󰕌 Cancel"

options="$lock\n$sleep\n$logout\n$restart\n$shutdown\n$cancel"

confirm() {
	confirmation="$(echo -e "Yes\nNo" | rofi -dmenu -theme "$rofi_dir/scripts/wayland/confirm-menu.rasi" &)"
	if [[ "$confirmation" != "Yes" ]]; then
		exit 0
	fi
}

answer="$(echo -e "$options" | rofi -dmenu -i -theme "$rofi_dir/scripts/wayland/powermenu.rasi")"

case $answer in
$lock)
	confirm
	playerctl pause
	sleep 0.4
	~/.config/wm/scripts/swaylock.sh
	;;
$sleep)
	confirm
	sleep 0.4
	~/.config/wm/scripts/swaylock.sh sleep
	notify-send "System slept! (unimplemented)"
	#hyprctl dispatch dpms off --does swayidle handle dpms on or does Hyprland?
	#systemctl suspend --NVIDIA OPEN DRIVERS DON'T SUSPEND
	;;
$logout)
	confirm
	notify-send "Logged out! (unimplemented)"
	#waiting for a login manager to be setup (stop lazy jack)
	;;
$restart)
	confirm
	systemctl reboot
	;;
$shutdown)
	confirm
	systemctl poweroff
	;;
$cancel)
	exit 0
	;;
esac
