#!/usr/bin/env sh
#
# script name: rofi-nerd-icons (wayland)
# description: pick from a list of nerd font icons
# usage: rofi-nerd-icons [paste]
# dependencies: rofi, awk, tr, wl-clipboard
# TODO: auto-paste the selection

main() {
	rofi -dmenu -p "Icon 󰄾" <~/.config/rofi/scripts/nerd-icons |
		awk '{ print $1 }' |
		tr -d '\n' |
		wl-copy
}

main
