name: Base Setup
package:
  - alacritty
  - appimage-manager
  - appimagelauncher
  - atool
  - bzip2
  - ccache
  - curl
  - docker
  - docker-compose
  - git
  - gparted
  - gzip
  - htop
  - jdk-openjdk
  - jq
  - lsof
  - neofetch
  - neovim
  - p7zip
  - p7zip-gui
  - pacman-contrib
  - pkgstats
  - python
  - rclone
  - tar
  - unrar
  - unzip
  - webp-pixbuf-loader
  - wget
  - xz
  - yadm
  - zip
commands:
  - base-add-herecura.sh
  - base-configuration.sh
