# completions for conf function
complete -c conf -f -a "vim" -d "open vim config"
complete -c conf -f -a "vm" -d "open vim maps config"
complete -c conf -f -a "vp" -d "open vim plug config"
complete -c conf -f -a "omf" -d "open omf config"
complete -c conf -f -a "oa" -d "open omf alias config"
complete -c conf -f -a "oaa" -d "open omf abbreviation config"
complete -c conf -f -a "ob" -d "open omf before init config"
complete -c conf -f -a "oe" -d "open omf env config"
complete -c conf -f -a "op" -d "open omf path config"
complete -c conf -f -a "tmux" -d "open tmux config"
complete -c conf -f -a "i3" -d "open i3 config"
complete -c conf -f -a "poly" -d "open polybar config"
complete -c conf -f -a "pl" -d "open polybar launch script"
complete -c conf -f -a "ranger" -d "open ranger config"
complete -c conf -f -a "rr" -d "open ranger rifle config"
complete -c conf -f -a "rs" -d "open ranger scope script"
complete -c conf -f -a "alacritty" -d "open alacritty config"
complete -c conf -f -a "sxhkd" -d "open sxhkd config"
