name: Base Module
depends:
  - cli
  - fortune
  - js
packages:
  - atool
  - btop
  - bzip2
  - ccache
  - curl
  - git
  - gzip
  - htop
  - jq
  - keychain
  - lsb-release
  - lsof
  - neofetch
  - neovim
  - p7zip
  - pacman-contrib
  - pkgstats
  - python
  - rclone
  - tar
  - transcrypt
  - unrar
  - unzip
  - wget
  - xz
  - yadm
  - yq
  - zip
commands:
  - base-add-herecura.sh
  - base-configuration.sh
