name: Dev Tools
packages:
  - docker
  - docker-compose
  - nodejs
  - npm
  - python
  - python-pip
  - shellcheck
  - sublime-text-4
  - visual-studio-code-insiders-bin
  - yarn
commands:
  - yarn global add neovim
