#!/usr/bin/env zsh

# function to shame the user for forgetting they weren't in vim
not-vim () {
    # make sure cowsay is installed
    if [[ -z $commands[cowsay] ]]; then
        echo "cowsay is not installed"
        return 1
    fi

    # do the thing
    cowsay "You're not in vim idiot, you're in your shell!"
}
