#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true

    # autocomplete method
    autocomplete_method = "coc"

    # font
    guifont = 'DankMono Nerd Font'

    # use nerdtree instead of vimfiler
    filemanager = "nerdtree"

    # use ale instead of neomake
    lint_engine = "ale"

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "checkers"

[[layers]]
name = "colorscheme"

[[layers]]
name = "debug"

[[layers]]
name = "format"

[[layers]]
name = "fzf"

[[layers]]
name = "git"
git_plugin = "fugitive"

[[layers]]
name = "gtags"
gtagslabel = "ctags"

[[layers]]
name = 'incsearch'

[[layers]]
name = "lang#c"
clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    cpp = "gnu++17"

[[layers]]
name = "shell"
default_position = "bottom"
default_height = 30

[[layers]]
name = "sudo"

[[layers]]
name = "tmux"

[[layers]]
name = "ui"
enable_scrollbar = true

[[layers]]
name = "VersionControl"
