#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # spacevim bootstrap functions
  bootstrap_before = 'bootstrap#before'
  bootstrap_after = 'bootstrap#after'

  # colour settings
  colorscheme = "onedark"
  # colorscheme = "challenger_deep"
  colorscheme_bg = "dark"
  enable_guicolors = true

  # status line config
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_tabline_ft_icon = true
  enable_statusline_mode = true
  enable_os_fileformat_icon = true
  enable_vimfiler_filetypeicon = true
  enable_vimfiler_gitstatus = true

  # font for gui version
  guifont = 'DankMono Nerd Font'

  # use defx instead of vimfiler
  filemanager = "defx"
  filetree_direction = "left"

  # use coc instead of deoplete
  autocomplete_method = "coc"

  # use ale instead of neomake
  lint_engine = "ale"

  # set my github username
  github_username = "redxtech"

    # challenger deep colour palette
    # custom_color_palette = [
        # ["#282828", "#a89984", 246, 235],
        # ["#a89984", "#504945", 239, 246],
        # ["#a89984", "#3c3836", 237, 246],
        # ["#665c54", 241],
        # ["#282828", "#83a598", 235, 109],
        # ["#282828", "#fe8019", 235, 208],
        # ["#282828", "#8ec07c", 235, 108],
        # ["#282828", "#689d6a", 235, 72],
        # ["#282828", "#8f3f71", 235, 132],
    # ]

# Enable autocomplete layer
[[layers]]
  name = "autocomplete"
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "checkers"

[[layers]]
  name = "colorscheme"

# [[layers]]
  # name = "debug"

[[layers]]
  name = "default"

[[layers]]
  name = "denite"

[[layers]]
  name = "format"

[[layers]]
  name = "git"
  git_plugin = "fugitive"

[[layers]]
  name = "github"

[[layers]]
  name = "gtags"
  # gtagslabel = "ctags"

[[layers]]
  name = "incsearch"

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    cpp = "gnu++17"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"
  enable_typeinfo = true
  enabled_linters = ['python', 'pylint']

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lsp"
  filetypes = [
    "cpp",
    "python",
    "sh"
  ]

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 30

[[layers]]
  name = "sudo"

[[layers]]
  name = "tmux"

[[layers]]
  name = "VersionControl"

[[custom_plugins]]
  name = "challenger-deep"
  repo = "challenger-deep-theme/vim"
  normalized_name = "challenger-deep"
  merged = false

[[custom_plugins]]
  repo = "ap/vim-css-color"
  merged = false

[[custom_plugins]]
  repo = "NoahTheDuke/vim-just"
  merged = false

[[custom_plugins]]
  repo = "zinit-zsh/zinit-vim-syntax"
  merged = false

