#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# get number of monitors
if test "$(hostname)" = "desktop"; then
	# bspc monitor -d I II III IV V VI VII VIII IX X
	bspc monitor DisplayPort-0 -d I II III IV V VI
	bspc monitor DisplayPort-1 -d VII VIII IX X
elif test "$(hostname)" = "laptop"; then
	bspc monitor -d I II III IV V VI VII VIII IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# Global Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^3'
bspc rule -a Element desktop='^3'
bspc rule -a Plexamp state=floating
bspc rule -a mpv:\*:Webcam state=floating

# Computer Specific Rules
if test "$(hostname)" = "desktop"; then
	# bspc rule -a Spotify desktop='^12'
	bspc rule -a Plex desktop='^9'
	bspc rule -a plexmediaplayer desktop='^9'
elif test "$(hostname)" = "laptop"; then
	# bspc rule -a spotify desktop='^4'
	bspc rule -a Plex desktop='^4'
	bspc rule -a plexmediaplayer desktop='^4'
fi

# External rules
bspc config external_rules_command "$HOME/.config/bspwm/scripts/bspwm_external_rules"


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# TODO right click menu, jgmenu?
# TODO pre-defined layouts?

#
# Autostart
#

# Run the autostart script
sh ~/.config/wm/scripts/autorun.sh

