#! /bin/sh

# start sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

# get number of monitors
if test "$(hostname)" = "desktop"; then
	# bspc monitor -d I II III IV V VI VII VIII IX X
	bspc monitor DisplayPort-0 -d shell www chat files five six
	bspc monitor DisplayPort-1 -d r-www music video ten
elif test "$(hostname)" = "laptop"; then
	bspc monitor -d shell www chat files music video seven eight nine ten
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
# bspc config ignore_ewmh_focus true

# global Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a obsidian state=floating sticky=on hidden=on
bspc rule -a obsidian desktop='^4'
bspc rule -a discord desktop='^3' follow=off
bspc rule -a Element desktop='^3' follow=off
bspc rule -a Slack state=floating
bspc rule -a Plexamp state=floating
bspc rule -a Subl desktop="*"
bspc rule -a flameshot state=floating
bspc rule -a "Blueman-manager" state=floating
bspc rule -a "mpv:*:Webcam" state=floating
bspc rule -a "*:*:Picture in picture" state=floating
bspc rule -a "*:*:Open Files" desktop="*" state=floating

# computer Specific Rules
if test "$(hostname)" = "desktop"; then
	bspc rule -a Spotify desktop='^8'
	bspc rule -a Plex desktop='^9'
	bspc rule -a plexmediaplayer desktop='^9'
elif test "$(hostname)" = "laptop"; then
	# bspc rule -a spotify desktop='^4'
	bspc rule -a Plex desktop='^4'
	bspc rule -a plexmediaplayer desktop='^4'
fi

# border
bspc config focused_border_color "#6c71c4"
bspc config normal_border_color "#073642"
bspc config active_border_color "#073642"

# TODO right click menu, jgmenu?
# TODO pre-defined layouts?

# arange monitors
if test "$(hostname)" = "desktop"; then
	if test -f ~/.screenlayout/desktop.sh; then
		sh ~/.screenlayout/desktop.sh
	fi
	bspc wm --reorder-monitors DisplayPort-0 DisplayPort-1
elif test "$(hostname)" = "laptop"; then
	if test -f ~/.screenlayout/laptop.sh; then
		sh ~/.screenlayout/laptop.sh
	fi
fi

# run the autostart script
sh ~/.config/wm/scripts/autorun.sh
