#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# Global Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^3'

# Computer Specific Rules
if test "$(hostname)" = "desktop"; then
	bspc rule -a Spotify desktop='^12'
	bspc rule -a plexmediaplayer desktop='^13'
elif test "$(hostname)" = "laptop"; then
	bspc rule -a Spotify desktop='^4'
	bspc rule -a plexmediaplayer desktop='^4'
fi



# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# TODO: right click menu, jgmenu?
# TODO: pre-defined layouts?

#
# Autostart
#

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# sh ~/.config/wm/scripts/screenlayout.sh

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
~/.fehbg &
# nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Compositor
picom -CGb --experimental-backend &

# Network Applet
nm-applet --indicator &

# Bluetooth Applet
blueman-applet &

# Cursor
xsetroot -cursor_name left_ptr &

# Trackpad
sh ~/.config/wm/scripts/natural-scrolling.sh

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

