#!/usr/bin/env bash
#
# script name: rofi-colour
# description: presents a list of colours to copy one to clipboard
# usage: rofi-colour [paste]
# dependencies: rofi, xclip, awk, tr

# list of colours
declare -A COLOURS
COLOURS=(
  ["blue"]="#6272a4"
	["cyan"]="#8be9fd"
	["green"]="#50fa7b"
	["orange"]="#ffb86c"
	["pink"]="#ff79c6"
  ["purple"]="#bd93f9"
	["red"]="#ff5555"
	["yellow"]="#f1fa8c"
	["black"]="#000000"
	["white"]="#ffffff"
	["bg"]="#282a36"
  ["fg"]="#f8f8f2"
)

# output a list of the colours next to their hex values
get_colours () {
	for c in "${!COLOURS[@]}"; do
		printf "$c => %s\n" "${COLOURS[$c]}"
	done
}

main () {
	selection="$(get_colours | rofi -theme pink-dracula -dmenu -p "Color" | awk '{ print $1 }')"

	echo "${COLOURS["$selection"]}" | tr -d '\n' | xclip -selection clip
}

main

