#!/usr/bin/env sh
#
# script name: rofi-youtube
# description: simple client to stream and download youtube videos
# usage: rofi-youtube <watch|download>
# dependencies: rofi, yt-dlp, dunstify, jq, choose, urlencode, curl

# exit on first error
set -e

main () {
	# grab the mode
	mode="$1"

	# make sure a mode is specified
	if test -z "$mode"; then
		echo "you need to specify a mode"
		return 1
	fi
 
	# choose a prompt
	case $1 in
		watch)
			prompt="Stream YT"
			;;
		download|dl)
			prompt="Download YT"
			;;
	esac

	# get the query
	if test -z "$2"; then
		query="$(rofi -theme red-dracula -dmenu -l 0 -p "$prompt ")"
	else
		shift 1
		query="$*"
	fi

	# turn the query into a url
	YT_API_KEY="$(cat "$HOME/.config/api_keys/YT_API_KEY")"
	query="$(printf "%s" "$query" | urlencode)"
	urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"
	
	# fetch and parse the result
	search_selection="$(curl -s "$urlstring" \
		| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) => youtu.be/\(.id.videoId)"' \
		| rofi -theme red-dracula -dmenu -i -p 'Choose Video ')"

	# selected result
	search_result="$(echo "$search_selection" | awk '{print $NF}')"

	# url of the youtube video
	url="https://$search_result"

	# grab the name of the video
	selection_name="$(echo "$search_selection" | choose -f " => " 1)"

	# select the mode and play the file with mpv or download it with yt-dlp
	case $mode in 
		watch)
			mpv "$url"
			;;
		download|dl)
			if test "$(pwd)" = "$HOME"; then
				dl_path="$HOME/Drives/Big Goober/Videos/YT/%(uploader)s/%(upload_date>%Y-%m-%d)s - %(title)s (%(id)s).%(ext)s"
			else
				dl_path="[%(uploader)s] - %(upload_date>%Y-%m-%d)s - %(title)s (%(id)s).%(ext)s"
			fi
			yt-dlp \
				--output "$dl_path" \
				--audio-quality 0 \
				--embed-sub \
				--embed-thumbnail \
				--embed-chapters \
				--embed-info-json \
				--sponsorblock-mark all \
				"$url"
			dunstify \
				--appname=YT-DLP \
				--icon=download \
				"YouTube video downloaded" \
				"The YouTube video ($selection_name) has been downloaded."
			;;
		*)
			echo "not a valid subcommand"
			return 1
			;;
	esac
}

main "$@"

