#!/usr/bin/env sh
#
# script name: rofi-moji
# description: select from a list of emojis
# usage rofi-moji
# dependencies: rofi, xclip, dunst, grep, sed, tr
# todo: generate a better, more complete, list of emojis

# exit on first error
set -e

# the famous "get a menu of emojis to copy" script.
main () {
	# choose an emoji the list
	chosen=$(grep -v "#" ~/.config/rofi/scripts/unicode | rofi -theme yellow-dracula -dmenu -i -l 20 -p "Emoji ")

	# copy to clipboard
	c=$(echo "$chosen" | sed "s/ .*//")
	echo "$c" | tr -d '\n' | xclip -selection clipboard
	dunstify "'$c' copied to clipboard." &

	# copy to primary
	# s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
	# echo "$s" | tr -d '\n' | xclip
	# dunstify "'$s' copied to primary." &
}

main

