#! /bin/bash

# New Computer Setup (Bootstrap) Script

# Store distro as variable.
DISTRO=$(cat /etc/os-release | grep \^ID= | tr -d ID=)

# Install fish to run rest of bootstrap process.
echo Installing fish shell...
if [ $DISTRO == arch ]; then
  echo Running \'sudo pacman -S fish\'
  sudo pacman -S fish
fi

if [ $DISTRO == ubuntu ]; then
  echo Adding fish-shell ppa...
  sudo apt-add-repository ppa:fish-shell/release-3
  echo Updating sources...
  sudo apt update
  echo Running \'sudo apt install fish\'
  sudo apt install fish
fi

echo Fish shell has been installed!
echo Switching shell...
echo source $HOME/.yadm/bs/bootstrap.fish | fish

echo screenfetch | fish
