#! /bin/bash

# New Computer Setup (Bootstrap) Script

# Store distro as variable.
DISTRO=$(cat /etc/os-release | grep \^ID= | tr -d ID=)

echo Currently running: $DISTRO

echo Running pre-install scripts...

source $HOME/.yadm/bs/pre-install.sh
source $HOME/.yadm/bs/$DISTRO/pre-install.sh

echo Installing packages from system package manager...

$PACKAGES+="audacity bitwarden bzip2 chromium-widevine cowsay discord docker docker-compose firefox firefox-developer edition fish flameshot git gitflow-ahv gnome-terminal guake htop kitty megasync neovim octave plex-media-player rclone qdirstat rustup spotify steam thefuck wget yay"

# if $DISTRO == arch
#   pacaur -Syu $PACKAGES
# else if $DISTRO == ubuntu
#   sudo apt update
#   sudo apt install $PACKAGES
# fi

echo Running post-install scripts...

source $HOME/.yadm/bs/post-install.sh
source $HOME/.yadm/bs/$DISTRO/post-install.sh

echo Bootstrapping completed!
