#! /bin/bash

# New Computer Setup (Bootstrap) Script

# Store distro as variable.
DISTRO=$(cat /etc/os-release | grep \^ID= | tr -d ID=)

# Install fish to run rest of bootstrap process.
echo Installing fish shell...
if [ $DISTRO == arch ]; then
  echo Running \'sudo pacman -S fish\'
  echo sudo pacman -S fish --noconfirm | sh
fi

if [ $DISTRO == ubuntu ]; then
  echo Adding fish-shell ppa...
  echo sudo apt-add-repository ppa:fish-shell/release-3 | sh
  echo Updating sources...
  echo sudo apt update | sh
  echo Running \'sudo apt install fish\'
  echo sudo apt install fish -y | sh
fi

echo Fish shell has been installed!
echo Switching shell...
echo source $HOME/.yadm/bs/bootstrap.fish | fish

